name: go_router_builder
description: >-
  A builder that supports generated strongly-typed route helpers for
  package:go_router
version: 3.0.1
repository: https://github.com/flutter/packages/tree/main/packages/go_router_builder
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+go_router_builder%22

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  analyzer: ">=7.6.0 <8.0.0"
  async: ^2.8.0
  # The upper bound is to work around a breaking change in `build` that was not
  # versioned according to semver, and broke `build_test` 2.x. See
  # https://github.com/flutter/flutter/issues/170832
  build: ^3.0.0
  build_config: ^1.1.2
  collection: ^1.17.1
  meta: ^1.16.0
  path: ^1.9.1
  source_gen: ^3.0.0
  source_helper: ^1.3.6

dev_dependencies:
  build_test: ^3.3.0
  dart_style: '>=3.1.1 <4.0.0'
  flutter:
    sdk: flutter
  go_router: ^16.1.0
  leak_tracker_flutter_testing: ">=3.0.10"
  package_config: ^2.2.0
  pub_semver: ^2.2.0
  test: ^1.26.3

topics:
  - codegen
  - deep-linking
  - go-router
  - navigation
